---
output: stevetemplates::cover_letter
geometry: margin = 1cm
header-includes:
  - \linespread{1.05}

author: Jonathan A. Pedroza, PhD
address: |
    | 14032 Gridley Rd
    | Norwalk, CA, 90650
email: "cpppedroza@gmail.com"
url: "jonathan-a-pedroza.netlify.app"
phone: (562) 547-5729
fontsize: 10pt
mainfont: cochineal
monofont: Fira Code
colorlinks: TRUE
citecolor: blue
urlcolor: blue
linkcolor: blue

fontawesome: FALSE
date: "`r format(Sys.time(), '%d %B %Y')`"
greetings: "Dear CSULA,"

---

```{r setup, include = FALSE}
jobtitle <- "Senior Research Analyst"
place <- "CSULA"
mission <- "to create data-driven decisions to promote growth in student success, enrollment, and institutional effectiveness"
skills <- "quantitative and qualitative research, statistical analyses, and dissemination of findings"
```

I am a past graduate of the CSU system and a Prevention Scientist with research interests in Latinx populations. I am pleased to submit my application for the opening of *`r jobtitle`* at `r place`. This position is of great interest to me due to `r place`'s mission `r mission`. I believe my skills in `r skills`, along with my willingness to learn can be beneficial to `r place`'s mission goals. 

As a traditionally trained academic, I am experienced in conducting both quantitative and qualitative research. In my graduate studies, I have worked on and led several research projects. I was the project coordinator for a community research project assessing food access in rural Oregon communities where I built strategic partnerships with community members. Additionally, I supervised a research study examining cognitive processes in college students with differing levels of technology use. In addition to these projects I have also collaborated with other researchers on projects examining environmental factors that influence county-level physical activity rates, examining health behaviors in Latinx populations, evaluating college student mental and physical health, and substance use in high-risk adolescent populations. I have expertise in hypothesis testing, conducting literature reviews, creating and testing surveys using programs like Qualtrics, creating experimental designs, community-based research, and conducting inferential statistics. While less versed in qualitative research skills, I have created interview/focus group questionnaires and have led interviews and focus groups. I also have some experience conducting thematic analyses from qualitative data.  

Aligned with the responsibilities of the position, I have expertise in conducting inferential statistics. I am fluent in both base R and the tidyverse, SPSS, and have proficiency using Python syntax for analyses. I have several years of experience conducting inferential statistics, including methods such as structural equation modeling and mixed-effect modeling. I have also created an R package used for regression diagnostics (https://github.com/jpedroza1228/reg.diagnostics). I have used inferential statistics to answer research questions about psychometrics of measures, as well as the previously mentioned research areas through published peer-reviewed journals and poster and paper presentations at regional and national conferences. I have also been nominated as runner-up in competitions on presentations for the American Public Health Association's Physical Activity section and the Society of Prevention Research's Sloboda and Bukoski Cup, where I presented on Medicare big data that was distributed to teams a month in advance. Through these mediums, I have used inferential statistics to discuss the relevance and potential implications of findings to audiences of academics and practitioners. 

My expertise in research and analyses also translate to my teaching. Over the past year, I have been teaching inferential statistics and experimental design. There, I have advanced the program curriculum by incorporating R rather than solely SPSS. In this course, I taught students the importance of ethics in conducting statistics and developing a true experiment. Students also learned how to create feasible research questions and hypotheses, utilize psychological theories, conduct comprehensive literature reviews, create a confidential survey using Qualtrics, conduct analyses appropriate for their experimental design, write a report of their findings, and prepare a presentation about their experiments for an academic conference.

In addition to my research and analytic skills, I have advanced competency using R for the past 4 years to create visualizations of analytic findings using dashboards and reproducible reports. In collaboration with the Vice Provost of University of Oregon's Graduate School, I created a dashboard (https://jpedroza1228.github.io/gradschool_dashboard/) to create growth models examining if increasing graduate teaching employees as instructors increased undergraduate student success. The dashboard included summarized analyses and visualizations exemplifying the relationship. Outside of my work as a lecturer, I sought out data from my department to examine trends in student success data, such as evaluating the non-passing rate of students in core Cal Poly Pomona Psychology courses. 

I believe I can be a great asset to `r place` with my skills in `r skills`, while learning more about utilizing these techniques to advance `r place`'s effectiveness and learning new tools. This opportunity will augment my current experience, knowledge, and skills through learning how to use these skills in collaboration with other analysts and stakeholders. Thank you for your consideration.

Best regards,

Jonathan A. Pedroza (JP), PhD
