---
output: stevetemplates::cover_letter
geometry: margin = 1in
header-includes:
  - \linespread{1.05}

author: Jonathan A. Pedroza, PhD
address: |
    | 14032 Gridley Rd
    | Norwalk, CA, 90650
email: "cpppedroza@gmail.com"
url: jonathan-a-pedroza.netlify.app
phone: (562) 547-5729
fontsize: 10pt
mainfont: cochineal
monofont: Fira Code

fontawesome: TRUE
date: "`r format(Sys.time(), '%d %B %Y')`"
greetings: "To whom it may concern,"

---

```{r setup, include = FALSE}
place <- "Varsity Tutors"
jobtitle <- "Data Scientist"
mission <- "to provide a personalized online learning environment for all"
skills <- "statistical inference, machine learning, R programming, and experimental design"
```

I am pleased to submit my application for the opening of `r jobtitle` at `r place`. This position is of great interest to me as an instructor, due to Nerdy and `r place`'s mission `r mission`. I believe my skills in `r skills`, along with my willingness to learn can be beneficial to `r place`'s mission goals.  

Aligned with the responsibilities of the position, I have expertise in conducting inferential statistics and machine learning algorithms using R and Python. Although my degree is not in a specific quantitative field, my program had an emphasis on learning several inferential techniques, including structural equation modeling and mixed-effect modeling. I have used inferential statistics to answer research questions about adolescent substance use, physical activity, and food access in rural Oregon through published peer-reviewed journals and poster and paper presentations at regional and national conferences. While being predominately trained in inferential statistics, I have sought out courses and a specialization in data science to learn more about machine learning. Through these data science courses, I have learned several machine learning algorithms in R; however during my personal time I have been teaching myself how to conduct these analyses in Python. I have used competitions, like Kaggle, to practice these analyses in both languages and am constantly researching more about these analyses through books and online resources.  

My expertise in these techniques also translate to my teaching and mentoring experiences. Over the past year, I have been teaching inferential statistics to undergraduate students. There, I have advanced the program curriculum by incorporating the use of R in addition to using SPSS. In addition to teaching inferential statistics, I taught experimental design to students. In this course, I taught students how to create an ethical research study by creating a true experiment using other university undergraduate students. Topics included whether their research question would be best answered using a between- or within-subjects design, how to conduct their own analyses, and how to construct a written report of their findings. 

In addition to my experiences using R and Python for modeling purposes, I have advanced competency using R for the past 4 years to create visualizations of analytic findings using dashboards and reproducible reports. In collaboration with the Vice Provost of University of Oregon's Graduate School, I created a dashboard to created growth models examining if increasing graduate teaching employees as instructors increased undergraduate student success. The dashboard included summarized analyses and visualizations exemplifying the relationship. 

Coming from an academic background, I believe I can be a great asset to `r place` with my skills and expertise in inferential statistics and machine learning, while learning more about utilizing these techniques with a business mindset. This opportunity will augment my current experience, knowledge, and skills through learning how to use these analyses to better support `r place` learners and promoting growth of the company. Thank you for your consideration.

Best regards,

Jonathan A. Pedroza (JP), PhD
