---
output: stevetemplates::cover_letter
geometry: margin = 1cm
header-includes:
  - \linespread{1.05}

author: Jonathan A. Pedroza, PhD
address: |
    | 14032 Gridley Rd
    | Norwalk, CA, 90650
email: "cpppedroza@gmail.com"
url: "jonathan-a-pedroza.netlify.app"
phone: (562) 547-5729
fontsize: 10pt
mainfont: cochineal
monofont: Fira Code
colorlinks: TRUE
citecolor: blue
urlcolor: blue
linkcolor: blue

fontawesome: FALSE
date: "`r format(Sys.time(), '%d %B %Y')`"
greetings: "Dear WestEd,"

---

```{r setup, include = FALSE}
jobtitle <- "Improvement Analytics Specialist"
place <- "WestEd"
mission <- "to improve learning, healthy development, and equity in schools and communities of need"
skills <- "research, evaluation, analytics, and programming"
```

I am pleased to submit my application for the opening of *`r jobtitle`* at `r place`. This position is of great interest to me due to `r place`'s mission `r mission`. I believe my skills and training as a Prevention Scientist in `r skills`, along with desire to reduce inequities, can be beneficial to `r place`'s mission goals. 

As an academic, I am experienced in conducting quantitative and qualitative research. I have worked on and led several research projects focused on inequities in specific populations. I am particularly passionate about the impact that social determinants of health, such as access to parks, pollution, and violent crime, have on health behaviors and chronic health conditions. Informed by the Social Ecological Model, I gave a presentation on twitter about this topic (https://twitter.com/PaSectionAPHA/status/1309192269447143425). My expertise in quantitative research also translates to my teaching. Over the past year, I have been teaching classes in inferential statistics and experimental design in Cal Poly Pomona's Psychology department. I taught students the importance of ethics in conducting statistics and developing an experiment. Students also learned how to create feasible research questions and hypotheses, utilize psychological theories, conduct comprehensive literature reviews, create a confidential survey using Qualtrics, conduct analyses appropriate for their study's design, write a report of their findings, and prepare a presentation about their studies for an academic conference. 

While less versed in qualitative research skills, I have created interview/focus group questionnaires and have led interviews and focus groups. I also have some experience conducting thematic analyses from qualitative data. I am proficient in navigating clearinghouses and reviews of evidence-based practices and programs’ effectiveness. As a graduate student, I was the project coordinator for a community research project assessing food access in rural Oregon communities. I built strategic partnerships with community members which aided in the identification of key stakeholders and increased access to the inclusion of community members in survey and focus group participation. In addition to working with rural communities, I have collaborated with the local public health department to assess parents' knowledge of materials provided to children promoting health behavior change using the evidence-based program CATCH. 

Recently, I have become more interested in the field of education and student success due to working as Diversity & Inclusion Graduate Employee at the University of Oregon. In this role, I provided safe spaces for graduate students to discuss concerns that informed the Graduate Diversity Advisory Council, a program I co-created with my supervisor. I assisted in organizing meetings with key departments based on student needs–primarily addressing issues of COVID-19 complications, issues of student safety based on race/gender identity discrimination and violence, and international student housing. 

My experience working for the university led to my interest in finding data to examine on student success. I have advanced competency using R for the past 4 years for data visualizations, dashboard creation, and statistical analyses, with proficiency in Python. In collaboration with the Vice Provost of University of Oregon's Graduate School, I developed a dashboard (https://jpedroza1228.github.io/gradschool_dashboard/) examining if increasing graduate teaching employees as instructors increased undergraduate student success. To practice creating interactive dashboards, I gathered exit data for graduating graduate students on the effectiveness and inclusivity of their respective programs (https://jp-shinyapps.shinyapps.io/shiny/). Outside of my work as a lecturer, I compiled data on student success at Cal Poly Pomona to evaluate non-passing rates of students. I have several years of experience conducting inferential statistics, including methods such as structural equation modeling and mixed-effect modeling. I have used inferential statistics to answer research questions about psychometrics of measures, adolescent and adult health behaviors, food access in rural Oregon, among other topics through published peer-reviewed journals and poster and paper presentations at regional and national conferences. Through these mediums, I have used inferential statistics to discuss the relevance and potential implications of findings to audiences of academics and practitioners.

I believe I can be a great asset to `r place` with my skills in `r skills`, while learning more about the promotion of equity in schools. This opportunity will augment my current experience, knowledge, and skills through learning how to use these skills in collaboration with other analysts and stakeholders. Thank you for your consideration.

Best regards,

Jonathan A. Pedroza (JP), PhD
